# SwiftLint Configuration for MacOSAIDiskCleaner

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo

# Opt-in rules
opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing

# Included paths
included:
  - MacOSAIDiskCleaner
  - MacOSAIDiskCleanerTests

# Excluded paths
excluded:
  - MacOSAIDiskCleaner/Generated
  - MacOSAIDiskCleaner/Extensions
  - .build
  - build
  - DerivedData

# Line length
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 100
  error: 200

# Type body length
type_body_length:
  warning: 400
  error: 800

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting depth
nesting:
  type_level:
    warning: 2
  warning: 3

# Custom rules
custom_rules:
  # Add project-specific rules here

# Identifier naming
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - URL

# Type names
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Large tuple
large_tuple:
  warning: 3
  error: 4
